server:
  port: 8085

spring:
  application:
    name: DELIVERY-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/bouquet_delivery_db
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: false